# File Paths
data_path: "data/split-dataset"
repos_path: "data/"
model_name: "deepseek-ai/deepseek-coder-1.3b-instruct"
output_dir: "models/proofmindrl"
train_type: grpo

# Training Args
hard_seq_len: 4096
per_device_train_batch_size: 4
learning_rate: 1.0e-4
num_train_epochs: 1
max_steps: 64500
peft_lora_r: 64
peft_lora_alpha: 16

temperature: 1.0
num_generations: 4
gradient_accumulation_steps: 2

# Basic
# example_collator:
#   alias: basic
#   state_tokens: 2640
#   script_tokens: 1320
#   out_tokens: 128 

# Proofs And Premises
example_collator:
   alias: proof-premise
   state_tokens: 1024 
   script_tokens: 512
   proof_tokens: 1024 
   premise_tokens: 512 
   out_tokens: 128 

# Premises only
# example_collator:
#   alias: premise
#   state_tokens: 1024 
#   script_tokens: 512
#   premise_tokens: 1536 
#   out_tokens: 128 

# Proofs only
# example_collator:
#  alias: proof 
#  state_tokens: 1024 
#  script_tokens: 512
#  proof_tokens: 1536 
#  out_tokens: 128 

# Prev lines 
# example_collator:
#   alias: n-prev-line 
#   state_tokens: 1024 
#   script_tokens: 512
#   prefix_tokens: 1536
#   out_tokens: 128 
#   data_loc: raw-data/coq-dataset
#   line_dict_loc: data/line-dict.json

# Evaluation Args
eval_steps: 100 
save_steps: 1000
eval_accumulation_steps: 1
per_device_eval_batch_size: 8
num_eval_examples: 2000 # Evaluation would take ~2 hours each time w/o limiting this

# Logging Args
logging_steps: 5
save_total_limit: 2

# Train from checkpoint
checkpoint_name: models/deepseek-bm25-proof-tfidf-proj-thm-prem-final/checkpoint-54500
